/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jp_co_drecom_jniexample_Jni */

#ifndef _Included_jp_co_drecom_jniexample_Jni
#define _Included_jp_co_drecom_jniexample_Jni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jp_co_drecom_jniexample_Jni
 * Method:    native_javaCallNative
 * Signature: (I)V
 */
JNIEXPORT jint JNICALL Java_jp_co_drecom_jniexample_Jni_native_1javaCallNative
  (JNIEnv *, jclass, jint);

/*
 * Class:     jp_co_drecom_jniexample_Jni
 * Method:    native_initialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jp_co_drecom_jniexample_Jni_native_1initialize
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
